In [12]:
import os
import numpy as np
import pandas as pd
import numpy.linalg as LA
import matplotlib.pyplot as plt
from tqdm import tqdm
import re

In [2]:
pj = os.path.join

In [8]:
tes_data = pd.read_csv('tasasdeinteres.csv')

In [10]:
tes_data = pd.read_csv('tasasdeinteres.csv')
tes_data['Date'] = pd.to_datetime(tes_data['Periodo(MMM DD, AAAA)'])
tes_data.set_index('Date', inplace=True)

In [13]:
def extraer_plazo(nombre_columna):
    # Busca uno o más dígitos (\d+) en el texto
    match = re.search(r'(\d+)', nombre_columna)
    return int(match.group(1)) if match else nombre_columna

In [14]:
zero_yields_cols = [c for c in tes_data.columns if c.find('pesos')>-1]

zero_yields = tes_data[zero_yields_cols]

zero_yields = zero_yields.rename(columns={c: extraer_plazo(c) for c in zero_yields_cols})

In [17]:
zero_yields.head()

               1      5      10
Date
2003-01-02  10.75  15.42  14.69
2003-01-03  10.46  15.44  14.47
2003-01-07  10.68  15.10  15.57
2003-01-08  10.23  15.57  14.63
2003-01-09  10.32  15.33  15.54

In [33]:
par_yields_cols = [c for c in tes_data.columns if c.find('T Cupón')>-1]

par_yields = tes_data[par_yields_cols]

In [36]:
tes_data.columns

Index(['Periodo(MMM DD, AAAA)',
       'Tasa de interés Cero Cupón, Títulos de Tesorería (TES), pesos - 1 año',
       'Tasa de interés Cero Cupón, Títulos de Tesorería (TES), pesos - 5 años',
       'Tasa de interés Cero Cupón, Títulos de Tesorería (TES), pesos - 10 años',
       'Tasa de interés Cero Cupón, Títulos de Tesorería (TES), UVR - 1 año',
       'Tasa de interés Cero Cupón, Títulos de Tesorería (TES), UVR - 5 años',
       'Tasa de interés Cero Cupón, Títulos de Tesorería (TES), UVR - 10 años'],
      dtype='object')

In [34]:
par_yields.columns

Index([], dtype='object')

In [35]:
par_yields.head()

Empty DataFrame
Columns: []
Index: [2003-01-02 00:00:00, 2003-01-03 00:00:00, 2003-01-07 00:00:00, 2003-01-08 00:00:00, 2003-01-09 00:00:00]

In [16]:
start_date = par_yields[10].dropna().index[0]

KeyError: 10

In [ ]:
yields = par_yields[start_date:].dropna()

In [ ]:
yields.columns.rename('tenor', inplace=True)

In [ ]:
lag_deltay = yields.diff(1)
lead_deltay = lag_deltay.shift(-1)

In [ ]:
lead_deltay.columns.rename('Maturity', inplace=True)

In [ ]:
(lag_deltay[[2,3,5,7,10,30]].corr().round(3)*100)